In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/cs39aa/sample_submission.csv
/kaggle/input/cs39aa/train.csv
/kaggle/input/cs39aa/test.csv


In [2]:
df = pd.read_csv("/kaggle/input/cs39aa/train.csv")
#df.columns = ['label', 'text']
df.head()

sentiment                                               text
0  positive  @JetBlue @JayVig I like the inflight snacks! I...
1  positive  @VirginAmerica thanks guys! Sweet route over t...
2  negative  @USAirways Your exchange/credit policies are w...
3  negative  @USAirways but in the meantime I'll be sleepin...
4  negative  @VirginAmerica hold times at call center are a...

In [3]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoConfig, TrainingArguments, Trainer
from datasets import Dataset, load_metric

In [4]:
MODEL_NAME = "roberta-large"
MAX_LENGTH=50

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=3, max_length=MAX_LENGTH, output_attentions=False, output_hidden_states=False)

Downloading:   0%|          | 0.00/482 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/878k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/446k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.29M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

Some weights of the model checkpoint at roberta-large were not used when initializing RobertaForSequenceClassification: ['lm_head.bias', 'roberta.pooler.dense.weight', 'lm_head.layer_norm.bias', 'lm_head.dense.weight', 'lm_head.dense.bias', 'roberta.pooler.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.decoder.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-large and are newly initialized: ['classifier.dense.bias', 'classifie

In [5]:
classes = df.sentiment.unique().tolist()
class_tok2idx = dict((v, k) for k, v in enumerate(classes))
class_idx2tok = dict((k, v) for k, v in enumerate(classes))
print(class_tok2idx)
print(class_idx2tok)

{'positive': 0, 'negative': 1, 'neutral': 2}
{0: 'positive', 1: 'negative', 2: 'neutral'}


In [6]:
df['label'] = df['sentiment'].apply(lambda x: class_tok2idx[x])
df.head()

sentiment                                               text  label
0  positive  @JetBlue @JayVig I like the inflight snacks! I...      0
1  positive  @VirginAmerica thanks guys! Sweet route over t...      0
2  negative  @USAirways Your exchange/credit policies are w...      1
3  negative  @USAirways but in the meantime I'll be sleepin...      1
4  negative  @VirginAmerica hold times at call center are a...      1

In [7]:
sequence_0 = "@united I will never fly with you again. Period."
seq0_tokens = tokenizer(sequence_0, return_tensors="pt")
print(f"number of tokens in seq0 is {len(seq0_tokens['input_ids'].flatten())}")
print(seq0_tokens)
model(**seq0_tokens).logits

number of tokens in seq0 is 14
{'input_ids': tensor([[    0,  1039, 33557,    38,    40,   393,  3598,    19,    47,   456,
             4, 18365,     4,     2]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}


tensor([[-0.3385,  0.2881,  0.0958]], grad_fn=<AddmmBackward0>)

In [8]:
sequence_1 = "@united Delayed flight, but you did the best you could. Thank you united crew."
seq1_tokens = tokenizer(sequence_1, return_tensors="pt")
print(f"number of tokens in seq1 is {len(seq1_tokens['input_ids'].flatten())}")
model(**seq1_tokens).logits

number of tokens in seq1 is 21


tensor([[-0.3232,  0.3165,  0.0504]], grad_fn=<AddmmBackward0>)

In [9]:
sequence_2 = "@united There is a reason why a only fly united, you're the best!"
seq2_tokens = tokenizer(sequence_2, return_tensors="pt")
print(f"number of tokens in seq2 is {len(seq2_tokens['input_ids'].flatten())}")
model(**seq2_tokens).logits

number of tokens in seq2 is 19


tensor([[-0.3887,  0.1567,  0.1571]], grad_fn=<AddmmBackward0>)

In [10]:
ds_raw = Dataset.from_pandas(df[['label','text']])
ds_raw[0]

{'label': 0,
 'text': "@JetBlue @JayVig I like the inflight snacks! I'm flying with you guys on 2/28! #JVMChat"}

In [11]:
def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True, max_length=MAX_LENGTH)

ds = ds_raw.map(tokenize_function, batched=True)

  0%|          | 0/10 [00:00<?, ?ba/s]

In [12]:
ds[0]

{'label': 0,
 'text': "@JetBlue @JayVig I like the inflight snacks! I'm flying with you guys on 2/28! #JVMChat",
 'input_ids': [0,
  1039,
  21608,
  17858,
  787,
  27918,
  846,
  1023,
  38,
  101,
  5,
  4047,
  6991,
  14967,
  328,
  38,
  437,
  4731,
  19,
  47,
  1669,
  15,
  132,
  73,
  2517,
  328,
  849,
  863,
  20954,
  29665,
  2,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 'attention_mask': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0]}

In [13]:
ds = ds.shuffle(seed=42)
ds[0]

{'label': 1,
 'text': '@AmericanAir 11 out of 11 delayed flights, you suck and getting worse',
 'input_ids': [0,
  1039,
  4310,
  17906,
  365,
  66,
  9,
  365,
  5943,
  4871,
  6,
  47,
  23829,
  8,
  562,
  3007,
  2,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 'attention_mask': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0]}

In [14]:
train_prop = 0.85
ds_train = ds.select(range(int(len(ds)*train_prop)))
ds_eval = ds.select(range(int(len(ds)*train_prop), len(ds)))

In [15]:
print(f"len(ds_train) = {len(ds_train)}")
print(f"len(ds_eval) = {len(ds_eval)}")

len(ds_train) = 8500
len(ds_eval) = 1500


In [16]:
import os
os.environ["WANDB_DISABLED"] = "true"

In [17]:
metric = load_metric("accuracy")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

training_args = TrainingArguments(num_train_epochs=4, 
                                  do_train=True,
                                  report_to=None,
                                  learning_rate=1.06e-5,
                                  adam_epsilon=2.05e-5,
                                  output_dir="/kaggle/tmp",
                                  evaluation_strategy="steps",
                                  eval_steps=500,
                                  per_device_train_batch_size=10,
                                  per_device_eval_batch_size=10)

trainer = Trainer(model = model, 
                  args = training_args,
                  train_dataset = ds_train, 
                  eval_dataset = ds_eval,
                  compute_metrics = compute_metrics,
)


torch.set_grad_enabled(True)
trainer.train()
trainer.evaluate()

Using the `WAND_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
The following columns in the training set don't have a corresponding argument in `RobertaForSequenceClassification.forward` and have been ignored: text. If text are not expected by `RobertaForSequenceClassification.forward`,  you can safely ignore this message.
/opt/conda/lib/python3.7/site-packages/transformers/optimization.py:310: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,
***** Running training *****
  Num examples = 8500
  Num Epochs = 4
  Instantaneous batch size per device = 10
  Total train batch size (w. parallel, distributed & accumulation) = 10
  Gradient Accumulation steps = 1
  Total optimiz

The following columns in the evaluation set don't have a corresponding argument in `RobertaForSequenceClassification.forward` and have been ignored: text. If text are not expected by `RobertaForSequenceClassification.forward`,  you can safely ignore this message.
***** Running Evaluation *****
  Num examples = 1500
  Batch size = 10
Saving model checkpoint to /kaggle/tmp/checkpoint-500
Configuration saved in /kaggle/tmp/checkpoint-500/config.json
Model weights saved in /kaggle/tmp/checkpoint-500/pytorch_model.bin
The following columns in the evaluation set don't have a corresponding argument in `RobertaForSequenceClassification.forward` and have been ignored: text. If text are not expected by `RobertaForSequenceClassification.forward`,  you can safely ignore this message.
***** Running Evaluation *****
  Num examples = 1500
  Batch size = 10
Saving model checkpoint to /kaggle/tmp/checkpoint-1000
Configuration saved in /kaggle/tmp/checkpoint-1000/config.json
Model weights saved in /kagg

{'eval_loss': 0.48736730217933655,
 'eval_accuracy': 0.906,
 'eval_runtime': 9.088,
 'eval_samples_per_second': 165.053,
 'eval_steps_per_second': 16.505,
 'epoch': 4.0}

In [18]:
df_test = pd.read_csv("/kaggle/input/cs39aa/test.csv")
df_test.head()

id                                               text
0   0                  @JetBlue okay awesome! Thank you!
1   1  @SouthwestAir wanting a ⭐️ for the ✈️ finding ...
2   2  @united Funny thing happened, we arrived on ou...
3   3               @united 2nd Late Flight flight today
4   4  @USAirways your service at PHL is abysmal. An ...

In [19]:
ds_test_raw = Dataset.from_pandas(df_test)
ds_test_raw[0]

{'id': 0, 'text': '@JetBlue okay awesome! Thank you!'}

In [20]:
ds_test = ds_test_raw.map(tokenize_function, batched=True)

  0%|          | 0/3 [00:00<?, ?ba/s]

In [21]:
preds = trainer.predict(test_dataset=ds_test)

The following columns in the test set don't have a corresponding argument in `RobertaForSequenceClassification.forward` and have been ignored: text, id. If text, id are not expected by `RobertaForSequenceClassification.forward`,  you can safely ignore this message.
***** Running Prediction *****
  Num examples = 3000
  Batch size = 10


In [22]:
test_preds = np.apply_along_axis(np.argmax, 1, preds.predictions) 
#ds_test['preds'] = pd.Series(test_preds.tolist())

In [23]:
df_test['preds'] = test_preds.tolist()
df_test['sentiment'] = df_test['preds'].apply(lambda x: class_idx2tok[x])
df_test.head()

id                                               text  preds sentiment
0   0                  @JetBlue okay awesome! Thank you!      0  positive
1   1  @SouthwestAir wanting a ⭐️ for the ✈️ finding ...      1  negative
2   2  @united Funny thing happened, we arrived on ou...      2   neutral
3   3               @united 2nd Late Flight flight today      1  negative
4   4  @USAirways your service at PHL is abysmal. An ...      1  negative

In [24]:
df_submission = df_test[['id','sentiment']]
df_submission.head()

id sentiment
0   0  positive
1   1  negative
2   2   neutral
3   3  negative
4   4  negative

In [25]:
df_submission.to_csv('submission.csv', index=False)